# ETL dos dados do KOPPEN - 2013

**Fonte**: https://forest-gis.com/classificacao-climatica-de-koppen-geiger-em-shapefile/

## Setup

In [127]:
# Necessário pandas `pip install pandas`
# -- Imports --
import pandas as pd
import janitor

In [ ]:
# -- Variáveis --
df_controle = pd.read_csv("../municipios_brasil_original.csv",decimal=",", index_col=1)
df = pd.read_excel("../koppen/Koppen Brazilian municipalities.xls", sheet_name="Data", index_col = 1)
# Rio de Janeiro é duplicado...
df.drop_duplicates(inplace=True)

df_join = df_controle.join(df)
df_join['koppen_cod'] = df_join['Köppen'].astype('category').cat.codes

df_join.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40 entries, 1600105 to 3205309
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   municipio_nome     40 non-null     object
 1   temperatura_anual  20 non-null     float64
 2   populacao          40 non-null     float64
 3   IDHM               40 non-null     int64
 4   PIB_per_capita     40 non-null     float64
 5   Municipality       38 non-null     object
 6   State              38 non-null     object
 7   Region             38 non-null     object
 8   Köppen             38 non-null     object
 9   Altitude           38 non-null     float64
 10  T_jan              38 non-null     float64
 11  T_feb              38 non-null     float64
 12  T_mar              38 non-null     float64
 13  T_apr              38 non-null     float64
 14  T_may              38 non-null     float64
 15  T_jun              38 non-null     float64
 16  T_jul              38 non-null     float64
 17  T_aug              38 non-null     float64
 18  T_sep              38 non-null     float64
 19  T_oct              38 non-null     float64
 20  T_nov              38 non-null     float64
 21  T_dec              38 non-null     float64
 22  R_jan              38 non-null     float64
 23  R_feb              38 non-null     float64
 24  R_mar              38 non-null     float64
 25  R_apr              38 non-null     float64
 26  R_may              38 non-null     float64
 27  R_jun              38 non-null     float64
 28  R_jul              38 non-null     float64
 29  R_aug              38 non-null     float64
 30  R_sep              38 non-null     float64
 31  R_oct              38 non-null     float64
 32  R_nov              38 non-null     float64
 33  R_dec              38 non-null     float64
 34  koppen_cod         40 non-null     int8
dtypes: float64(28), int64(1), int8(1), object(5)
memory usage: 12.0+ KB

In [114]:
df_join.head()

,municipio_nome,temperatura_anual,populacao,IDHM,PIB_per_capita,Municipality,State,Region,Köppen,Altitude,...,R_apr,R_may,R_jun,R_jul,R_aug,R_sep,R_oct,R_nov,R_dec,koppen_cod
municipio_id,,,,,,,,,,,,,,,,,,,,,
1600105,Amapa,26.0,733.8,642,27.6,Amapá,AP,Norte,Am,32.977505,...,454.994385,502.083496,352.574951,266.872375,131.634979,50.952412,36.023254,74.646660,179.130753,1
2800308,Aracaju,NaN,602.8,770,37.0,Aracaju,SE,Nordeste,Am,7.911602,...,210.083328,283.561096,215.044449,200.616669,120.288887,90.105553,58.972221,56.205555,46.933334,1
1702208,Araguatins,24.0,31.9,631,14.5,Araguatins,TO,Norte,Aw,152.335342,...,238.345474,81.163727,24.790838,7.476906,11.412317,47.509575,86.993240,143.903122,212.113403,3
3506003,Bauru,22.0,379.0,801,54.5,Bauru,SP,Sudeste,Cfa,532.107910,...,64.961273,56.240665,53.965424,40.426003,32.031811,68.899033,129.287689,153.582291,226.764862,4
1501402,Belém,NaN,1303.4,746,31.1,Belém,PA,Norte,Am,8.206128,...,443.886719,354.629517,179.579391,170.070572,129.484680,97.110489,62.026928,93.887650,185.294342,1

## Temperatura anual das cidades

In [128]:
df_final: pd.DataFrame = df_join[['municipio_nome','PIB_per_capita','populacao', 'IDHM', 'Altitude', 'temperatura_anual', 'koppen_cod']]
df_final

,municipio_nome,PIB_per_capita,populacao,IDHM,Altitude,temperatura_anual,koppen_cod
municipio_id,,,,,,,
1600105,Amapa,27.6,733.8,642,32.977505,26.0,1
2800308,Aracaju,37.0,602.8,770,7.911602,NaN,1
1702208,Araguatins,14.5,31.9,631,152.335342,24.0,3
3506003,Bauru,54.5,379.0,801,532.107910,22.0,4
1501402,Belém,31.1,1303.4,746,8.206128,NaN,1
3106200,Belo Horizonte,56.2,2315.6,810,909.062683,23.0,6
1400100,Boa Vista,44.1,413.5,752,87.631096,NaN,1
5300108,Brasília,129.8,2817.3,824,1034.792358,21.0,3
5002704,Campo Grande,47.1,898.1,784,467.670349,NaN,1
5103007,Chapada Dos Guimaraes,95.7,19.0,688,462.114838,24.0,3
4204251,Cocal Do Sul,62.9,17.2,780,101.548782,19.0,4
3120003,Corrego Novo,14.3,2.9,632,356.293854,21.0,3
5103403,Cuiabá,60.0,650.9,785,280.317627,NaN,3
4106902,Curitiba,67.9,1773.7,823,914.698181,18.0,5
2605459,Fernando De Noronha,73.0,3.2,788,NaN,26.0,-1
4205407,Florianopolis,58.0,537.2,847,45.051182,20.0,4
2304400,Fortaleza,35.8,2428.7,754,25.343948,NaN,2
5208707,Goiania,52.7,1437.2,799,791.762268,24.0,3
2606408,Gravata,18.9,86.5,634,459.719177,23.0,2
3518800,Guarulhos,75.5,1291.7,763,806.539124,20.0,5
2204709,Inhuma,12.7,15.0,624,466.209229,26.0,2
2507507,João Pessoa,34.1,833.9,763,31.380733,NaN,2
1600303,Macapá,41.7,442.9,733,16.714241,NaN,1
2704302,Maceió,35.2,957.9,721,58.913460,NaN,1
1302603,Manaus,61.9,2063.7,737,66.969734,NaN,0
2408102,Natal,41.5,751.3,763,40.888889,NaN,2
1721000,Palmas,46.8,302.7,788,409.909241,NaN,3
4314902,Porto Alegre,78.6,1332.8,805,41.343155,NaN,4
1100205,Porto Velho,55.2,460.4,736,120.262291,NaN,1
2611606,Recife,44.6,1488.9,772,32.915180,NaN,1
1200401,Rio Branco,35.5,364.7,727,209.034378,NaN,1
3304557,Rio De Janeiro,73.0,6730.7,799,85.396645,25.0,1
2927408,Salvador,31.7,2417.7,759,17.677155,NaN,0
3548500,Santos,73.9,418.6,840,260.663483,23.0,0
3458807,Sao Caetano Do Sul,136.0,165.7,854,NaN,19.5,-1
2111300,São Luís,40.8,1037.8,768,15.089156,NaN,3
3550308,São Paulo,93.2,11452.0,805,777.808899,NaN,5
3552205,Sorocaba,81.3,762.1,798,624.695557,20.0,4
2211001,Teresina,34.0,866.3,751,113.306656,NaN,3
3205309,Vitoria,85.0,322.9,845,22.086021,24.0,1

In [129]:
nova_temp = df_join.filter(like='T_').mean(axis=1)
df_final['temperatura_anual'] = nova_temp.combine_first(df_join['temperatura_anual'])

/tmp/ipykernel_89520/3081447080.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['temperatura_anual'] = nova_temp.combine_first(df_join['temperatura_anual'])

In [130]:
df_final

,municipio_nome,PIB_per_capita,populacao,IDHM,Altitude,temperatura_anual,koppen_cod
municipio_id,,,,,,,
1600105,Amapa,27.6,733.8,642,32.977505,27.284206,1
2800308,Aracaju,37.0,602.8,770,7.911602,25.950050,1
1702208,Araguatins,14.5,31.9,631,152.335342,27.405858,3
3506003,Bauru,54.5,379.0,801,532.107910,20.934916,4
1501402,Belém,31.1,1303.4,746,8.206128,27.934292,1
3106200,Belo Horizonte,56.2,2315.6,810,909.062683,19.095724,6
1400100,Boa Vista,44.1,413.5,752,87.631096,25.424889,1
5300108,Brasília,129.8,2817.3,824,1034.792358,20.960918,3
5002704,Campo Grande,47.1,898.1,784,467.670349,22.322037,1
5103007,Chapada Dos Guimaraes,95.7,19.0,688,462.114838,24.567049,3
4204251,Cocal Do Sul,62.9,17.2,780,101.548782,19.205852,4
3120003,Corrego Novo,14.3,2.9,632,356.293854,21.962842,3
5103403,Cuiabá,60.0,650.9,785,280.317627,25.250469,3
4106902,Curitiba,67.9,1773.7,823,914.698181,17.092006,5
2605459,Fernando De Noronha,73.0,3.2,788,NaN,26.000000,-1
4205407,Florianopolis,58.0,537.2,847,45.051182,20.139250,4
2304400,Fortaleza,35.8,2428.7,754,25.343948,26.962661,2
5208707,Goiania,52.7,1437.2,799,791.762268,22.143502,3
2606408,Gravata,18.9,86.5,634,459.719177,23.154877,2
3518800,Guarulhos,75.5,1291.7,763,806.539124,18.380448,5
2204709,Inhuma,12.7,15.0,624,466.209229,24.859044,2
2507507,João Pessoa,34.1,833.9,763,31.380733,25.866837,2
1600303,Macapá,41.7,442.9,733,16.714241,27.594642,1
2704302,Maceió,35.2,957.9,721,58.913460,25.564946,1
1302603,Manaus,61.9,2063.7,737,66.969734,26.768356,0
2408102,Natal,41.5,751.3,763,40.888889,26.029958,2
1721000,Palmas,46.8,302.7,788,409.909241,25.666572,3
4314902,Porto Alegre,78.6,1332.8,805,41.343155,18.558548,4
1100205,Porto Velho,55.2,460.4,736,120.262291,25.858499,1
2611606,Recife,44.6,1488.9,772,32.915180,25.762086,1
1200401,Rio Branco,35.5,364.7,727,209.034378,24.446041,1
3304557,Rio De Janeiro,73.0,6730.7,799,85.396645,22.116413,1
2927408,Salvador,31.7,2417.7,759,17.677155,25.758699,0
3548500,Santos,73.9,418.6,840,260.663483,21.067167,0
3458807,Sao Caetano Do Sul,136.0,165.7,854,NaN,19.500000,-1
2111300,São Luís,40.8,1037.8,768,15.089156,27.815948,3
3550308,São Paulo,93.2,11452.0,805,777.808899,18.432310,5
3552205,Sorocaba,81.3,762.1,798,624.695557,19.518679,4
2211001,Teresina,34.0,866.3,751,113.306656,27.137427,3
3205309,Vitoria,85.0,322.9,845,22.086021,23.259832,1

In [133]:
df_final['chuva_anual'] = df_join.filter(like='R_').mean(axis=1)

/tmp/ipykernel_89520/807827021.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['chuva_anual'] = df_join.filter(like='R_').mean(axis=1)

## Conserta nome e exporta CSV

In [136]:
df_final.columns = df_final.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

In [137]:
df_final.dropna(inplace=True)
df_final

/tmp/ipykernel_89520/3494360828.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.dropna(inplace=True)

,municipio_nome,pib_per_capita,populacao,idhm,altitude,temperatura_anual,koppen_cod,chuva_anual
municipio_id,,,,,,,,
1600105,Amapa,27.6,733.8,642,32.977505,27.284206,1,265.984365
2800308,Aracaju,37.0,602.8,770,7.911602,25.950050,1,125.298610
1702208,Araguatins,14.5,31.9,631,152.335342,27.405858,3,141.153402
3506003,Bauru,54.5,379.0,801,532.107910,20.934916,4,115.753342
1501402,Belém,31.1,1303.4,746,8.206128,27.934292,1,250.650572
3106200,Belo Horizonte,56.2,2315.6,810,909.062683,19.095724,6,128.863013
1400100,Boa Vista,44.1,413.5,752,87.631096,25.424889,1,150.697335
5300108,Brasília,129.8,2817.3,824,1034.792358,20.960918,3,127.622327
5002704,Campo Grande,47.1,898.1,784,467.670349,22.322037,1,134.005501
5103007,Chapada Dos Guimaraes,95.7,19.0,688,462.114838,24.567049,3,133.883487
4204251,Cocal Do Sul,62.9,17.2,780,101.548782,19.205852,4,121.164634
3120003,Corrego Novo,14.3,2.9,632,356.293854,21.962842,3,113.301738
5103403,Cuiabá,60.0,650.9,785,280.317627,25.250469,3,118.283530
4106902,Curitiba,67.9,1773.7,823,914.698181,17.092006,5,129.642026
4205407,Florianopolis,58.0,537.2,847,45.051182,20.139250,4,136.544350
2304400,Fortaleza,35.8,2428.7,754,25.343948,26.962661,2,116.884288
5208707,Goiania,52.7,1437.2,799,791.762268,22.143502,3,135.398796
2606408,Gravata,18.9,86.5,634,459.719177,23.154877,2,68.197975
3518800,Guarulhos,75.5,1291.7,763,806.539124,18.380448,5,120.701933
2204709,Inhuma,12.7,15.0,624,466.209229,24.859044,2,76.827847
2507507,João Pessoa,34.1,833.9,763,31.380733,25.866837,2,152.046635
1600303,Macapá,41.7,442.9,733,16.714241,27.594642,1,236.532787
2704302,Maceió,35.2,957.9,721,58.913460,25.564946,1,142.732847
1302603,Manaus,61.9,2063.7,737,66.969734,26.768356,0,202.196731
2408102,Natal,41.5,751.3,763,40.888889,26.029958,2,114.153293
1721000,Palmas,46.8,302.7,788,409.909241,25.666572,3,140.866778
4314902,Porto Alegre,78.6,1332.8,805,41.343155,18.558548,4,128.069350
1100205,Porto Velho,55.2,460.4,736,120.262291,25.858499,1,208.148564
2611606,Recife,44.6,1488.9,772,32.915180,25.762086,1,153.283850
1200401,Rio Branco,35.5,364.7,727,209.034378,24.446041,1,177.926619
3304557,Rio De Janeiro,73.0,6730.7,799,85.396645,22.116413,1,115.833334
2927408,Salvador,31.7,2417.7,759,17.677155,25.758699,0,153.971024
3548500,Santos,73.9,418.6,840,260.663483,21.067167,0,224.613952
2111300,São Luís,40.8,1037.8,768,15.089156,27.815948,3,169.047243
3550308,São Paulo,93.2,11452.0,805,777.808899,18.432310,5,141.447319
3552205,Sorocaba,81.3,762.1,798,624.695557,19.518679,4,107.972950
2211001,Teresina,34.0,866.3,751,113.306656,27.137427,3,122.297099
3205309,Vitoria,85.0,322.9,845,22.086021,23.259832,1,108.084281

In [139]:
df_final.to_csv('../municipios_brasil.csv', decimal=',')